---
- name: Downlaod files
  hosts: all

  tasks:
  - name: Download file
    get_url:
      url: https://www.python.org/ftp/python/3.12.2/Python-3.12.2.tar.xz
      dest: /tmp/script/
      owner: paul
      group: paul
      mode: 0777